contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #hicmap channel"
    url: https://nfcore.slack.com/channels/hicmap
    about: Discussion about the dhslab/hicmap pipeline
